In [1]:
import numpy as np

In [32]:
a = np.arange(24)
# print(a)
# a.ndim

b = a.reshape(2,2,3,2)
print(b)


[[[[ 0  1]
   [ 2  3]
   [ 4  5]]

  [[ 6  7]
   [ 8  9]
   [10 11]]]


 [[[12 13]
   [14 15]
   [16 17]]

  [[18 19]
   [20 21]
   [22 23]]]]


In [39]:
x = x = np.zeros((2,2), dtype=[('x', 'i4'), ('y', 'i4')])
print (x)

[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]
